version: '2.1'

volumes:
  pbft-shared:

services:
  simplewallet-processor:
    container_name: simplewallet-processor
    build:
      context: .
      dockerfile: ./pyprocessor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/simplewallet/'
  simplewallet-client:
    container_name: simplewallet-client
    build:
      context: .
      dockerfile: ./pyclient/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'http_proxy=${http_proxy}'
      - 'https_proxy=${https_proxy}'
      - 'no_proxy=rest-api,validator,${no_proxy}'
    volumes:
      - '.:/project/simplewallet/'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - rest-api
    entrypoint: "bash -c \"sawtooth keygen --force sawtooth && tail -f /dev/null\""
    stop_signal: SIGKILL
  rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://172.27.104.197:4004
        --bind 127.0.0.1:8008
  settings-tp:
    container_name: settings-tp
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://172.27.104.197:4004

# -------------=== shell ===-------------

  shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: sawtooth-shell-default
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

# -------------=== validators ===-------------
  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default
    expose:
      - 4004
      - 5050
      - 8800
    ports:
      - '4004:4004'
      - '5050:5050'
      - '8800:8800'
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator.priv ]; then
          cp /pbft-shared/validators/validator.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://172.27.104.197:8800 \
          --bind component:tcp://127.0.0.1:4004 \
          --bind consensus:tcp://127.0.0.1:5050 \
          --bind network:tcp://172.27.104.197:8800 \
          --scheduler parallel \
          --peering dynamic\
          --maximum-peer-connectivity 10000 \
          --seeds tcp://52.70.96.63:8800 \
          --network-auth trust 
      "
  pbft-1:
   image: hyperledger/sawtooth-pbft-engine:1.0
   container_name: sawtooth-pbft-engine-default
   command: pbft-engine -vv --connect tcp://127.0.0.1:5050
   stop_signal: SIGKILL
